server:
  additionalApplications:
  - name: calculator
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/timothyngo/infra.git
      targetRevision: HEAD
      path: base
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: calculator
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        prune: false
        selfHeal: true
